file(GLOB_RECURSE executables ${BINARY_DIR}/*${EXE_EXTENSION})
message(STATUS "executable files found: ${executables}")
file(GLOB dllfiles ${DLL_DIR}/*${DLL_EXTENSION})
message(STATUS "${DLL_DIR} contains dll files: ${dllfiles}")

foreach (executable ${executables}})
    get_filename_component(exedir ${executable} DIRECTORY)
    message(STATUS "executable directory = ${exedir}")
    foreach (dllfile ${dllfiles})
        file(COPY ${dllfile} DESTINATION ${exedir})
    endforeach()
endforeach()